# Phase 3: Optimization Configuration
# Bayesian optimization for best detection conditions

phase_name: "phase_3_optimization"
description: "Bayesian optimization for optimal detection parameters"

# Phase-specific parameters
convergence_threshold: 0.02
max_iterations: 20
parallel_workers: 8
priority: "optimization"

# Optimization strategy
optimization:
  method: "bayesian"
  acquisition_function: "EI"  # Expected Improvement
  n_initial_points: 10
  random_state: 42
  kappa: 1.96  # Exploration parameter

# Parameter space for optimization (further refined)
parameter_space:
  laser_intensity:
    refinement_factor: 0.3  # 70% reduction in range
    n_points: 12
    log_scale: true
    
  plasma_density:
    refinement_factor: 0.3
    n_points: 12
    log_scale: true
    
  temperature_constant:
    refinement_factor: 0.2
    n_points: 8
    log_scale: true
    
  magnetic_field:
    refinement_factor: 0.5
    n_points: 6
    log_scale: false

# Hybrid model enabled for optimization
physics:
  grid_points: 512  # High resolution
  save_graybody_figure: true
  enable_hybrid: true
  hybrid_model: "anabhel"
  mirror_D: 10e-6
  mirror_eta: 1.0
  use_fast_magnetosonic: true
  perform_kappa_inference: true
  inference_calls: 60
  inference_bounds: [1.0e5, 1.0e12]

# Detection settings for optimization
detection:
  significance_threshold: 5.0  # High threshold for optimization
  observation_time: 3600.0

# Convergence criteria
convergence:
  moving_average_window: 10
  improvement_threshold: 0.01
  min_samples_for_convergence: 20
  metric: "detection_time_improvement"

# Bayesian optimization settings
bayesian_optimization:
  n_calls: 50
  n_initial_points: 10
  noise: 1e-4
  acq_func: "EI"
  kappa: 1.96

# Result filtering for phase transition
phase_transition:
  min_success_rate: 0.3
  min_kappa_threshold: 1e10
  max_detection_time: 1e4  # seconds

# Performance settings
performance:
  timeout_per_simulation: 300
  progress_update_interval: 60
