name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible so we can reproduce and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm these before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have checked the documentation and FAQ
          required: true
        - label: I have installed the latest version
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: When I run `ahr quickstart`, I get a ValueError about array dimensions...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Install with `pip install -e .`
        2. Run `ahr quickstart --nx 500`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The command should complete successfully and create output files
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: |
        ```
        ValueError: operands could not be broadcast together with shapes (500,) (1000,)
        ```
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: macOS 14.0
        - Python: 3.11.5
        - Package version: 0.3.0
        - Installation: pip install -e .
        - GPU: None
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please include full error messages and logs
      placeholder: Paste error messages here (use triple backticks for formatting)
      render: shell

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Blocking (cannot use the software)
        - High (major functionality broken)
        - Medium (minor functionality broken)
        - Low (cosmetic or documentation)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI (command-line interface)
        - Horizon finding
        - Graybody models
        - Detection modeling
        - Parameter sweeps
        - Documentation
        - Installation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      description: Which parts of the validation suite pass?
      options:
        - label: `ahr validate` passes
        - label: `ahr quickstart` works
        - label: `ahr bench` runs
        - label: `pytest -q` passes

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context or information
      placeholder: This started happening after I upgraded from v0.2.0...
